<?php
$xmlstr=<<<XML
<?xml version='1.0' encoding='UTF-8'?>
<Outp xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    <Outps>
        <Tradeno>AA00001</Tradeno>
        <Ctmno>Y00001</Ctmno>
        <Tradedate>20220517</Tradedate>
        <Recpno>AA00000001</Recpno>
        <Addresss></Addresss>
        <Taxmark>2</Taxmark>
        <Amount>1500</Amount>
        <Tax>0</Tax>
        <Salesno>G00001</Salesno>
        <Stno>A01</Stno>
        <Moneypay>0</Moneypay>
        <Discount>0</Discount>
        <Tamount>1500</Tamount>
        <Remark></Remark>
        <Monthsec>202205</Monthsec>
        <Sendtype></Sendtype>
        <Tradetime>08:00</Tradetime>
        <Schno>02</Schno>
        <Machno></Machno>
        <Idno>12345678</Idno>
        <Cashpay>0</Cashpay>
        <Retcash>0</Retcash>
        <Crdno></Crdno>
        <Crdpay>0</Crdpay>
        <Billpay>0</Billpay>
        <Tkindno>網路訂單</Tkindno>
        <Prepay>0</Prepay>
        <Imaxno>2</Imaxno>
        <Deskno></Deskno>
        <Useno></Useno>
        <Bmaxno>0</Bmaxno>
        <Othpay1>0</Othpay1>
        <Othpay2>0</Othpay2>
        <Manqty>0</Manqty>
        <Outmark>0</Outmark>
        <Taxrate>5</Taxrate>
        <Othpay3>0</Othpay3>
        <Othpay4>0</Othpay4>
        <Othpay5>0</Othpay5>
        <Othpay6>0</Othpay6>
        <Atel>0226795661</Atel>
        <Aname>黃先生</Aname>
    </Outps>
    <OutpItem>
        <Line_no>1.0</Line_no>
        <Goodno>U0001</Goodno>
        <Saleprice>30</Saleprice>
        <Tradeqty>10</Tradeqty>
        <Cost>50</Cost>
        <Saleprice2>20</Saleprice2>
        <Rem></Rem>
        <Pkno>1</Pkno>
        <Goodname2>奶茶</Goodname2>
        <Oaddpri>10.0000</Oaddpri>
        <Omemo>大杯,冷飲</Omemo>
        <Mkdname>經典飲品</Mkdname>
    </OutpItem>
    <OutpItem>
        <Line_no>2.0</Line_no>
        <Goodno>U0002</Goodno>
        <Saleprice>25</Saleprice>
        <Tradeqty>10</Tradeqty>
        <Cost>50</Cost>
        <Saleprice2>20</Saleprice2>
        <Rem></Rem>
        <Pkno>2</Pkno>
        <Goodname2>德式香腸</Goodname2>
        <Oaddpri>5.0000</Oaddpri>
        <Omemo>茄汁肉醬_Bolognese</Omemo>
        <Mkdname>愜意點心</Mkdname>
    </OutpItem>
</Outp>
XML;
?>