<?php
include_once '../tool/dbTool.inc.php';
$conn=sqlconnect('localhost','','paperadmin','1qaz2wsx','utf-8','mysql');
$sql='CREATE DATABASE testDB CHARACTER SET utf8 COLLATE utf8_general_ci;';//新增DB
sqlnoresponse($conn,$sql,'mysql');
$sql="CREATE USER 'posdb'@'localhost' IDENTIFIED BY '1qaz2wsx'";//新增DB使用者帳號
print_r(sqlnoresponse($conn,$sql,'mysql'));
$sql="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, FILE, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON *.* TO 'posdb'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0";//給予該帳號權限
print_r(sqlnoresponse($conn,$sql,'mysql'));
sqlclose($conn,'mysql');
$conn=sqlconnect('localhost','testDB','posdb','1qaz2wsx','utf-8','mysql');
$sql='CREATE TABLE CST011 (
	TERMINALNUMBER		VARCHAR(8)		NOT NULL,
	BIZDATE				VARCHAR(8)		NOT NULL,
	CONSECNUMBER		VARCHAR(6)		NOT NULL,
	INVOICENUMBER		VARCHAR(6)		NOT NULL,
	INVOICEDATE			VARCHAR(8)		NOT NULL,
	INVOICETIME			VARCHAR(6)		NOT NULL,
	OPENCLKCODE			VARCHAR(10)		NOT NULL,
	CLKCODE				VARCHAR(10)		NOT NULL,
	CLKNAME				VARCHAR(24)		NOT NULL,
	REGMODE				VARCHAR(1)		NOT NULL,
	REGTYPE				VARCHAR(1)		NOT NULL,
	REGFUNC				VARCHAR(1)		NOT NULL,
	SALESTTLQTY			FLOAT			DEFAULT 0  NOT NULL,
	SALESTTLAMT			FLOAT			DEFAULT 0  NOT NULL,
	TAX1				FLOAT			DEFAULT 0  NOT NULL,
	TAX2				FLOAT			DEFAULT 0  NOT NULL,
	TAX3				FLOAT			DEFAULT 0  NOT NULL,
	TAX4				FLOAT			DEFAULT 0  NOT NULL,
	TAX5				FLOAT			DEFAULT 0  NOT NULL,
	TAX6				FLOAT			DEFAULT 0  NOT NULL,
	TAX7				FLOAT			DEFAULT 0  NOT NULL,
	TAX8				FLOAT			DEFAULT 0  NOT NULL,
	TAX9				FLOAT			DEFAULT 0  NOT NULL,
	TAX10				FLOAT			DEFAULT 0  NOT NULL,
	TA1					FLOAT			DEFAULT 0  NOT NULL,
	TA2					FLOAT			DEFAULT 0  NOT NULL,
	TA3					FLOAT			DEFAULT 0  NOT NULL,
	TA4					FLOAT			DEFAULT 0  NOT NULL,
	TA5					FLOAT			DEFAULT 0  NOT NULL,
	TA6					FLOAT			DEFAULT 0  NOT NULL,
	TA7					FLOAT			DEFAULT 0  NOT NULL,
	TA8					FLOAT			DEFAULT 0  NOT NULL,
	TA9					FLOAT			DEFAULT 0  NOT NULL,
	TA10				FLOAT			DEFAULT 0  NOT NULL,
	EX1					FLOAT			DEFAULT 0  NOT NULL,
	EX2					FLOAT			DEFAULT 0  NOT NULL,
	EX3					FLOAT			DEFAULT 0  NOT NULL,
	EX4					FLOAT			DEFAULT 0  NOT NULL,
	EX5					FLOAT			DEFAULT 0  NOT NULL,
	EX6					FLOAT			DEFAULT 0  NOT NULL,
	EX7					FLOAT			DEFAULT 0  NOT NULL,
	EX8					FLOAT			DEFAULT 0  NOT NULL,
	EX9					FLOAT			DEFAULT 0  NOT NULL,
	EX10				FLOAT			DEFAULT 0  NOT NULL,
	NONTAX				FLOAT			DEFAULT 0  NOT NULL,
	PROFITAMT			FLOAT			DEFAULT 0  NOT NULL,
	COVER				FLOAT			DEFAULT 0  NOT NULL,
	CUSTGPCODE			VARCHAR(2)		DEFAULT NULL,
	CUSTGPNAME			VARCHAR(24)		DEFAULT NULL,
	CUSTCODE			VARCHAR(20)		DEFAULT NULL,
	CUSTNAME			VARCHAR(40)		DEFAULT NULL,
	POINTTARGET			FLOAT			DEFAULT 0  NOT NULL,
	POINTPREVIOUS		FLOAT			DEFAULT 0  NOT NULL,
	POINTGOT			FLOAT			DEFAULT 0  NOT NULL,
	POINTUSED			FLOAT			DEFAULT 0  NOT NULL,
	OPENCHKDATE			VARCHAR(8)		DEFAULT NULL,
	OPENCHKTIME			VARCHAR(6)		DEFAULT NULL,
	NBCHKDATE			VARCHAR(8)		DEFAULT NULL,
	NBCHKTIME			VARCHAR(6)		DEFAULT NULL,
	NBCHKNUMBER			VARCHAR(6)		DEFAULT NULL,
	TABLENUMBER			VARCHAR(12)		DEFAULT NULL,
	RELINVOICEDATE		VARCHAR(8)		DEFAULT NULL,
	RELINVOICETIME		VARCHAR(6)		DEFAULT NULL,
	RELINVOICENUMBER	VARCHAR(6)		DEFAULT NULL,
	ZCOUNTER			VARCHAR(6)		DEFAULT NULL,
	REMARKS				VARCHAR(128)	DEFAULT NULL,
	CREATEDATETIME		VARCHAR(14)		NOT NULL,
	UPDATEDATETIME		VARCHAR(14)		NOT NULL,
	CREDITCARD			VARCHAR(4)		DEFAULT NULL,

	PRIMARY KEY (
		TERMINALNUMBER,
		BIZDATE,
		CONSECNUMBER,
		CREATEDATETIME
		)
	)';
sqlnoresponse($conn,$sql,'mysql');
$sql='CREATE TABLE CST012 (
		TERMINALNUMBER	VARCHAR(8)		NOT NULL,
		BIZDATE			VARCHAR(8)		NOT NULL,
		CONSECNUMBER	VARCHAR(6)		NOT NULL,
		LINENUMBER		VARCHAR(3)		NOT NULL,
		CLKCODE			VARCHAR(10)		NOT NULL,
		CLKNAME			VARCHAR(24)		NOT NULL,
		DTLMODE			VARCHAR(1)		NOT NULL,
		DTLTYPE			VARCHAR(1)		NOT NULL,
		DTLFUNC			VARCHAR(2)		NOT NULL,
		ITEMCODE		VARCHAR(16)		DEFAULT NULL,
		ITEMNAME		VARCHAR(24)		DEFAULT NULL,
		ITEMGRPCODE		VARCHAR(6)		DEFAULT NULL,
		ITEMGRPNAME		VARCHAR(24)		DEFAULT NULL,
		ITEMDEPTCODE	VARCHAR(6)		DEFAULT NULL,
		ITEMDEPTNAME	VARCHAR(24)		DEFAULT NULL,
		SELECTIVEITEM1	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM2	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM3	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM4	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM5	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM6	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM7	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM8	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM9	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM10	VARCHAR(6)		DEFAULT NULL,
		UNITQTY			FLOAT			DEFAULT 0  NOT NULL,
		UNITPRICELINK	VARCHAR(2)		DEFAULT NULL,
		WEIGHT			FLOAT			DEFAULT 0  NOT NULL,
		QTY				FLOAT			DEFAULT 0  NOT NULL,
		UNITPRICE		FLOAT			DEFAULT 0  NOT NULL,
		AMT				FLOAT			DEFAULT 0  NOT NULL,
		TAXCODE1		VARCHAR(2)		DEFAULT NULL,
		TAXCODE2		VARCHAR(2)		DEFAULT NULL,
		TAXCODE3		VARCHAR(2)		DEFAULT NULL,
		TAXCODE4		VARCHAR(2)		DEFAULT NULL,
		TAXCODE5		VARCHAR(2)		DEFAULT NULL,
		ZCOUNTER        VARCHAR(6)		DEFAULT NULL,
		REMARKS			VARCHAR(128)	DEFAULT NULL,
		CREATEDATETIME	VARCHAR(14)		NOT NULL,

		PRIMARY KEY (
			TERMINALNUMBER,
			BIZDATE,
			CONSECNUMBER,
			LINENUMBER,
			CREATEDATETIME
		)
	)';
sqlnoresponse($conn,$sql,'mysql');
$sql='CREATE TABLE CST013 (
		TERMINALNUMBER		VARCHAR(8)		NOT NULL,
		DATETIME			VARCHAR(14)		NOT NULL,
		CONSECNUMBER		VARCHAR(6)		NOT NULL,
		LINENUMBER			VARCHAR(3)		NOT NULL,
		DETAILINDEXTYPE		VARCHAR(2)		NOT NULL,
		CUSTCODE			VARCHAR(20)		DEFAULT NULL,
		QTY					FLOAT			NOT NULL,
		AMT					FLOAT			NOT NULL,
		LINKTERMINALNUMBER	VARCHAR(8)		DEFAULT NULL,
		LINKDATETIME		VARCHAR(14)		DEFAULT NULL,
		LINKCONSECNUMBER	VARCHAR(6)		DEFAULT NULL,
		LINKLINENUMBER		VARCHAR(3)		DEFAULT NULL,
		REMARKS				VARCHAR(128)	DEFAULT NULL,
		CREATEDATETIME		VARCHAR(14)		NOT NULL,
		UPDATEDATETIME		VARCHAR(14)		NOT NULL,

		PRIMARY KEY (
			TERMINALNUMBER,
			DATETIME,
			CONSECNUMBER,
			LINENUMBER
		)
	)';
sqlnoresponse($conn,$sql,'mysql');
$sql='CREATE TABLE Dummy (CODE VARCHAR (1))';
sqlnoresponse($conn,$sql,'mysql');
$sql='CREATE TABLE deleteCST012 (
		TERMINALNUMBER	VARCHAR(8)		NOT NULL,
		BIZDATE			VARCHAR(8)		NOT NULL,
		CONSECNUMBER	VARCHAR(6)		NOT NULL,
		LINENUMBER		VARCHAR(3)		NOT NULL,
		CLKCODE			VARCHAR(10)		NOT NULL,
		CLKNAME			VARCHAR(24)		NOT NULL,
		DTLMODE			VARCHAR(1)		NOT NULL,
		DTLTYPE			VARCHAR(1)		NOT NULL,
		DTLFUNC			VARCHAR(2)		NOT NULL,
		ITEMCODE		VARCHAR(16)		DEFAULT NULL,
		ITEMNAME		VARCHAR(24)		DEFAULT NULL,
		ITEMGRPCODE		VARCHAR(6)		DEFAULT NULL,
		ITEMGRPNAME		VARCHAR(24)		DEFAULT NULL,
		ITEMDEPTCODE	VARCHAR(6)		DEFAULT NULL,
		ITEMDEPTNAME	VARCHAR(24)		DEFAULT NULL,
		SELECTIVEITEM1	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM2	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM3	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM4	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM5	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM6	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM7	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM8	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM9	VARCHAR(6)		DEFAULT NULL,
		SELECTIVEITEM10	VARCHAR(6)		DEFAULT NULL,
		UNITQTY			FLOAT			DEFAULT 0  NOT NULL,
		UNITPRICELINK	VARCHAR(2)		DEFAULT NULL,
		WEIGHT			FLOAT			DEFAULT 0  NOT NULL,
		QTY				FLOAT			DEFAULT 0  NOT NULL,
		UNITPRICE		FLOAT			DEFAULT 0  NOT NULL,
		AMT				FLOAT			DEFAULT 0  NOT NULL,
		TAXCODE1		VARCHAR(2)		DEFAULT NULL,
		TAXCODE2		VARCHAR(2)		DEFAULT NULL,
		TAXCODE3		VARCHAR(2)		DEFAULT NULL,
		TAXCODE4		VARCHAR(2)		DEFAULT NULL,
		TAXCODE5		VARCHAR(2)		DEFAULT NULL,
		ZCOUNTER        VARCHAR(6)		DEFAULT NULL,
		REMARKS			VARCHAR(128)	DEFAULT NULL,
		CREATEDATETIME	VARCHAR(14)		NOT NULL,
		deletetime		TEXT
	)';
sqlnoresponse($conn,$sql,'mysql');
$sql="CREATE TABLE invlist (
		  invnumber		varchar(15)		NOT NULL,
		  createdate	varchar(10)		NOT NULL,
		  createtime	varchar(8)		NOT NULL,
		  buyerid		varchar(10)		NOT NULL,
		  buyname		varchar(20)		NOT NULL,
		  sellerid		varchar(10)		NOT NULL,
		  sellername	varchar(20)		NOT NULL,
		  relatenumber	varchar(20)		NOT NULL,
		  invtype		varchar(5)		NOT NULL DEFAULT '07',
		  donatemark	varchar(2)		NOT NULL,
		  carriertype	varchar(10)		DEFAULT NULL,
		  carrierid1	varchar(15)		DEFAULT NULL,
		  carrierid2	varchar(15)		DEFAULT NULL,
		  printmark		varchar(2)		NOT NULL,
		  npoban		varchar(10)		DEFAULT NULL,
		  randomnumber	varchar(4)		NOT NULL,
		  totalamount	int(11)			NOT NULL,
		  canceldate	varchar(10)		DEFAULT NULL,
		  canceltime	varchar(8)		DEFAULT NULL,
		  cancelreason	varchar(256)	DEFAULT NULL,
		  replaceinv	varchar(15)		DEFAULT NULL,
		  state			int(11)			NOT NULL DEFAULT '1',
		  PRIMARY KEY (
			invnumber,
			createdate,
			createtime,
			buyerid
		  )
	)";
sqlnoresponse($conn,$sql,'mysql');
$sql='CREATE TABLE number (
		  company	varchar(32) NOT NULL,
		  story		varchar(16) NOT NULL,
		  banno		varchar(10) NOT NULL,
		  datetime	varchar(5)	NOT NULL,
		  state		int(1)		NOT NULL,
		  PRIMARY KEY (
			banno
		  )
	)';
sqlnoresponse($conn,$sql,'mysql');
$sql='CREATE TABLE reprint (
		rdate		varchar(8)	NOT NULL, 
		rtime		varchar(8)	NOT NULL,
		invnumber	varchar(10) NOT NULL, 
		invdate		varchar(8)	DEFAULT NULL, 
		invimte		varchar(8)	NOT NULL,
		PRIMARY KEY (
			rdate,
			rtime,
			invnumber
		)
	)';
sqlnoresponse($conn,$sql,'mysql');
$sql='';
sqlnoresponse($conn,$sql,'mysql');
$sql='';
sqlnoresponse($conn,$sql,'mysql');
$sql='';
sqlnoresponse($conn,$sql,'mysql');
$sql='';
sqlnoresponse($conn,$sql,'mysql');
$sql='';
sqlnoresponse($conn,$sql,'mysql');
sqlclose($conn,'mysql');
?>